# Generated by Django 5.0 on 2023-12-23 10:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(60)], verbose_name='캐릭터 나이')),
                ('character_class', models.CharField(choices=[('Warrior', '전사'), ('Wizard', '마법사'), ('Archer', '궁수'), ('Rogue', '도적'), ('Priest', '사제'), ('Knight', '기사'), ('Bard', '바드'), ('Druid', '드루이드'), ('Summoner', '소환사'), ('Assassin', '암살자'), ('Sorcerer', '법사'), ('Paladin', '팔라딘'), ('Hunter', '사냥꾼'), ('Shaman', '주술사'), ('Gladiator', '전투사')], verbose_name='캐릭터 직업')),
                ('character_race', models.CharField(choices=[('Human', '인간'), ('Elf', '엘프'), ('Dwarf', '드워프')], verbose_name='캐릭터 종족')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='adventurer')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_content', models.TextField(verbose_name='Report Content')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.adventure', verbose_name='adventure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='adventurer')),
            ],
        ),
    ]
