# Generated by Django 5.0 on 2023-12-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='status',
            field=models.CharField(blank=True),
        ),
    ]
